language: node_js
env:
  - MOCHA_REPORTER=spec
node_js:
  - "0.11"
  - "0.10"
notifications:
  on_success: always
  on_failure: always
  on_start: always
  webhooks:
    - 'http://ngs-hubot.herokuapp.com/travisci/hooks'

